# Generated by Django 3.0.5 on 2020-05-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
