# Generated by Django 3.0.5 on 2020-05-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0003_listitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
