# Generated by Django 3.0.5 on 2020-05-10 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0004_auto_20200510_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='member',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
