# Generated by Django 3.0.5 on 2020-05-10 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0005_listitem_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
