# Generated by Django 3.0.5 on 2020-05-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0007_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
