# Generated by Django 3.0.5 on 2020-05-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mem_1',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mem_2',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mem_3',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
