# Generated by Django 3.0.5 on 2020-05-11 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BucketList', '0011_auto_20200512_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mem_1',
            new_name='mem',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mem_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mem_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
