# Generated by Django 3.0.5 on 2020-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0014_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='leader_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
