# Generated by Django 3.0.5 on 2020-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0017_auto_20200513_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
