# Generated by Django 3.0.5 on 2020-05-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0018_auto_20200513_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='status',
            field=models.TextField(default='Incomplete', max_length=20),
        ),
    ]
