# Generated by Django 3.0.5 on 2020-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucketList', '0019_listitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('end_time', models.TimeField(help_text='deadline', verbose_name='deadline')),
                ('notes', models.TextField(help_text='Textual Notes', verbose_name='Textual Notes')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
